name = "tetrashop100"
compatibility_date = "2025-11-04"
compatibility_flags = ["nodejs_compat"]

[vars]
PROJECT_NAME = "Tetrashop100"
PROJECT_VERSION = "1.0.0"
ENVIRONMENT = "production"

[[routes]]
pattern = "tetrashop100.ramin-edjlal1359.workers.dev/*"
custom_domain = true
